subdirs = ['heap', 'sched', 'test_run']

env = Environment(
    CC = 'gcc', 
    CFLAGS = '-g -Wall -Wextra', 
)
env.Decider('timestamp-match')
Export('env')

# Get a tuple of the objs and build each test
objs = SConscript(dirs=subdirs)
for o in objs:
    env.Program(o + Object('stubs.c'))
