subdirs = ['heap']

env = Environment(
    CC = 'gcc', 
    CFLAGS = '-g -Wall -Wextra', 
)
env.Decider('timestamp-match')
Export('env')
objs = SConscript(dirs=subdirs)
env.Program(objs + [Object('stubs.c')])
