Import('env')
heap_env = Environment(
    CC='gcc',
    CFLAGS='-g -Wall -Wextra -isystem ../include', # relative to test/
)
objs = [env.Object('main.c'), heap_env.Object(source='../../kernel/heap.c', 
        target='heap.o')]
Return('objs')
