Import('env')

# We need to remove loader.o from the returned objs since
# it is order-dependant
asm = Glob('*.asm', strings=True)
if 'loader.asm' in asm:
    asm.remove('loader.asm')

objs = Glob('*.c') + env.File(asm)
env.Object(objs)

# loader.o is still a dep
loader = env.Object('loader.asm')
env.Requires(objs, loader)

Return('objs')
