Import('env')

loader = 'loader.asm'

# We need to remove loader.o from the returned objs since
# it is order-dependant
asm = Glob('*.asm', strings=True)
if loader in asm:
    asm.remove(loader)

objs = Glob('*.c') + env.File(asm)
env.Object(objs)

# loader.o is still a dep
env.Object(loader)
env.Requires(objs, loader)

Return('objs')
